export const FRIEND_REQUESTS = "FRIEND_REQUESTS";
export const ADD_FRIEND = "ADD_FRIEND";
export const CURRENT_FRIENDS = "CURRENT_FRIENDS";
export const VIEW_FRIEND = "VIEW_FRIEND";
export const UPDATE_FRIEND_REQUEST = "UPDATE_FRIEND_REQUEST";