export const SPACE_NAME = "SPACE_NAME";
export const SPACE_DESC = "SPACE_DESC";
export const SPACE_CHALLENGERS = "SPACE_CHALLENGERS";
export const SEND_CURRENT_SPACES = "SEND_CURRENT_SPACES";
export const SEND_CURRENT_MEMBERS = "SEND_CURRENT_MEMBERS";
export const SELECTED_SPACE = "SELECTED_SPACE";
export const SINGLE_USER_IN_SPACE = "SINGLE_USER_IN_SPACE";

export const USERS_SPACES = "USERS_SPACES";
