export const CHOSEN_TASK_TYPE = "CHOSEN_TASK_TYPE";
export const CHOSEN_SPACE = "CHOSEN_SPACE";
export const CREATE_TASK_ITEM = "CREATE_TASK_ITEM";
export const SHOW_CHECKBOX_MODAL = "SHOW_CHECKBOX_MODAL";
export const SHOW_CHANGE_MODAL = "SHOW_CHANGE_MODAL";
export const SHOW_VIEW_MODAL = "SHOW_VIEW_MODAL";
export const RESET_TASK_CREATION = "RESET_TASK_CREATION";
export const END_DATE_CREATION = "END_DATE_CREATION";