export const USER_CREDENTIALS = "USER_CREDENTIALS";
export const USER_INCOMING_SPACE_INVITES = "USER_INCOMING_SPACE_INVITES";
export const USER_WITH_POPULATED_TASKS = "USER_WITH_POPULATED_TASKS";
export const SINGLE_USER_POPULATED_TASKS = "SINGLE_USER_POPULATED_TASKS";